### ISSUE TITLE
checkLabel 方法错误

### ISSUE THREAD

**Issue by xuanbo** [chenjiandongx/ginprom#1]
checkLabel 方法中使用

regexp.MatchString(label, pattern)

有误，参数写反。

应更正为 regexp.MatchString(pattern, label)

**Comment by chenjiandongx** [comment]
@xuanbo 感谢提醒，已修正 https://github.com/chenjiandongx/ginprom/commit/7cfb22707fa6bf600fc246c8abdaafbf7a1ec949
